name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event, running on a ${{ runner.os }} server"
      
      - run: echo "Checkout running!"
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - run: echo "Listing files!"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          
      - run: echo "This job's status is ${{ job.status }}. Running Super-Linter!"
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - run: echo "Running unittest!"
      - run: python -m unittest test.py
